import os,sys
sys.path.insert(1, './Generator')
from Generator import *

project_path="/home/edgar/Documents/Practicas/Laravel/"
project_name="Test"

database_name="Test"
database_user="edgar"
database_password="737"

models=[
	{
		"name":"User",
		"fields":[
			{
				"name":"id_user",
				"type":"increments",
				"primary":True,
				"references":{
					"name":"User_Post",
					"field":"id_user",
					"type":"hasOne",
				}
			},
			{
				"name":"email",
				"type":"string"
			},
			{
				"name":"password",
				"type":"string"
			}
		]
	},
	{
		"name":"Post",
		"fields":[
			{
				"name":"id_post",
				"type":"increments",
				"primary":True,
				"references":{
					"name":"User_Post",
					"field":"id_post",
					"type":"hasOne",
				}
			},
			{
				"name":"title",
				"type":"string",
				"primary":False,
			},
			{
				"name":"content",
				"type":"string"
			}
		]
	},
	{
		"name":"User_Post",
		"fields":[
			{
				"name":"id_user",
				"type":"integer",
				"constraint":["unsigned()"],
				"references":{
					"name":"User",
					"field":"id_user",
					"type":"belongsTo"
				}
			},
			{
				"name":"id_post",
				"type":"integer",
				"constraint":["unsigned()"],
				"references":{
					"name":"Post",
					"field":"id_post",
					"type":"belongsTo"
				}
			}
		]
	},
]
controllers=[
	{
		"name":"IndexController",
		"methods":[
			{
				"name":"index",
				"route":"/",
				"method":"GET",
				"type":"index", #blank,login,register,logout,index,select,create,update,delete,
				"view":"index",
			}
		]
	},
	{
		"name":"UserController",
		"model":"User",
		"methods":[
			{
				"name":"index",
				"route":"/users",
				"method":"GET",
				"middlewares":["login"],
				"type":"index",
				"view":"user",
				"request-type":"http" #ajax,http
			},
			{
				"name":"select",
				"route":"/users/{id_user}",
				"method":"GET",
				"path-params":["id_user"],
				"middlewares":["login"],
				"type":"select",
				"view":"user-individual"
			},
			{
				"name":"create",
				"route":"/users",
				"method":"POST",
				"middlewares":["login"],
				"type":"create",
				"request-type":"ajax"
			},
			{
				"name":"update",
				"route":"/users/update",
				"method":"POST",
				"body-params":["id_user"],
				"middlewares":["login"],
				"type":"update",
				"request-type":"ajax"
			},
			{
				"name":"delete",
				"route":"/users/delete",
				"method":"POST",
				"body-params":["id_user"],
				"middlewares":["login"],
				"type":"delete",
				"request-type":"ajax"
			}
		]
	},
	{
		"name":"PostController",
		"model":"Post",
		"methods":[
			{
				"name":"index",
				"route":"/posts",
				"method":"GET",
				"middlewares":["login"],
				"type":"index",
				"view":"post",
				"request-type":"http" #ajax,http
			},
			{
				"name":"select",
				"route":"/posts/{id_post}",
				"method":"GET",
				"path-params":["id_post"],
				"middlewares":["login"],
				"type":"select",
				"view":"post-individual"
			},
			{
				"name":"create",
				"route":"/posts",
				"method":"POST",
				"middlewares":["login"],
				"type":"create",
				"request-type":"ajax"
			},
			{
				"name":"update",
				"route":"/posts/update",
				"method":"POST",
				"body-params":["id_post"],
				"middlewares":["login"],
				"type":"update",
				"request-type":"ajax"
			},
			{
				"name":"delete",
				"route":"/posts/delete",
				"method":"POST",
				"body-params":["id_post"],
				"middlewares":["login"],
				"type":"delete",
				"request-type":"ajax"
			}
		]
	}
]

views=[
	{
		"name":"index",
		"folder":"index",
	},
	{
		"name":"user",
		"folder":"user",
		"components":["user-form"]
	},
	{
		"name":"user-individual",
		"folder":"user",
		"components":["user-form-individual"]
	},
	{
		"name":"post",
		"folder":"post",
		"components":["post-form"]
	},
	{
		"name":"post-individual",
		"folder":"post",
		"components":["post-form-individual"]
	}
]

components=[
	{
		"name":"user-form",
		"type":"complete", #blank,complete,individual
		"props":["users"],
	},
	{
		"name":"user-form-individual",
		"type":"individual",
		"props":["user"]
	},
	{
		"name":"post-form",
		"type":"complete", #blank,complete,individual
		"props":["posts"],
	},
	{
		"name":"post-form-individual",
		"type":"individual",
		"props":["post"]
	}
]


g=Generator(project_path,project_name)
g.init()
g.set_database(database_name,database_user,database_password)
g.use_login(True)

g.create_models(models)
g.create_migrations(models,False)

g.create_middlewares()
g.create_controllers(controllers,models,views)
g.create_route(controllers)

g.create_views(views,components)
g.create_components(components,views,controllers,models)
g.create_nav_bar(controllers)