import os,sys
sys.path.insert(1, './Generator')
from Generator import Generator

project_path="/home/edgar/Documents/Practicas/Laravel/"
project_name="Test"

database_name="Test"
database_user="edgar"
database_password="737"

models=[
	{
		"table_name":"User",
		"attributes":[
			{
				"name":"id_user",
				"type":"increments",
				"primary":True,
				"references":{
					"table_name":"User_Post",
					"field":"id_user",
					"type":"hasOne",
					"strong":True
				}
			},
			{
				"name":"email",
				"type":"string"
			},
			{
				"name":"password",
				"type":"string"
			}
		]
	},
	{
		"table_name":"Post",
		"attributes":[
			{
				"name":"id_post",
				"type":"increments",
				"primary":True,
				"references":{
					"table_name":"User_Post",
					"field":"id_post",
					"type":"hasOne",
					"strong":True
				}
			},
			{
				"name":"title",
				"type":"string",
				"primary":False,
			},
			{
				"name":"content",
				"type":"string"
			}
		]
	},
	{
		"table_name":"User_Post",
		"attributes":[
			{
				"name":"id_user",
				"type":"integer",
				"constraint":["unsigned()"],
				"references":{
					"table_name":"User",
					"field":"id_user",
					"type":"belongsTo",
					"strong":False
				}
			},
			{
				"name":"id_post",
				"type":"integer",
				"constraint":["unsigned()"],
				"references":{
					"table_name":"Post",
					"field":"id_post",
					"type":"belongsTo"
				}
			}
		]
	},
]

middlewares=[
	{
		"name":"LoginMiddleware",
		"alias":"login",
		"type":"login"
	}
]

controllers=[
	{
		"name":"IndexController",
		"methods":[
			{
				"route":"/",
				"method":"GET",
				"function":"index",
			}
		]
	},
	{
		"name":"LoginController",
		"model":"User",
		"methods":[
			{
				"route":"/login",
				"method":"GET",
				"function":"index"
			},
			{
				"route":"/login",
				"method":"POST",
				"function":"login",
				"body":["email","password"],
			},
			{
				"route":"/logout",
				"method":"GET",
				"function":"logout",
			}
		]
	},
	{
		"name":"RegisterController",
		"model":"User",
		"methods":[
			{
				"route":"/register",
				"method":"GET",
				"function":"index",
			},
			{
				"route":"/register",
				"method":"POST",
				"function":"register",
			}
		]
	},
	{
		"name":"UserController",
		"model":"User",
		"methods":[
			{
				"route":"/users",
				"method":"GET",
				"function":"index",
				"middlewares":["login"]
			},
			{
				"route":"/users/{id_user}",
				"method":"GET",
				"function":"select",
				"parameters":["id_user"],
				"middlewares":["login"]
			},
			{
				"route":"/users",
				"method":"POST",
				"function":"create",
				"middlewares":["login"]
			},
			{
				"route":"/users/update",
				"method":"POST",
				"function":"update",
				"body":["id_user"],
				"middlewares":["login"]
			},
			{
				"route":"/users/delete",
				"method":"POST",
				"function":"delete",
				"body":["id_user"],
				"middlewares":["login"]
			}
		]
	},
	{
		"name":"PostController",
		"model":"Post",
		"methods":[
			{
				"route":"/posts",
				"method":"GET",
				"function":"index",
				"middlewares":["login"]
			},
			{
				"route":"/posts/{id_post}",
				"method":"GET",
				"function":"select",
				"parameters":["id_post"],
				"middlewares":["login"]
			},
			{
				"route":"/posts",
				"method":"POST",
				"function":"create",
				"middlewares":["login"]
			},
			{
				"route":"/posts/update",
				"method":"POST",
				"function":"update",
				"body":["id_post"],
				"middlewares":["login"]
			},
			{
				"route":"/posts/delete",
				"method":"POST",
				"function":"delete",
				"body":["id_post"],
				"middlewares":["login"]
			}
		]
	}
]

views=[
	{
		"name":"index",
		"folder":"index"
	},
	{
		"name":"user",
		"folder":"user",
		"controller":"UserController",
		"components":[
			{
				"name":"user-form",
				"type":"complete",
				"model":"User",
				"props":["users"],
			}
		]
	},
	{
		"name":"user-individual",
		"folder":"user",
		"controller":"UserController",
		"components":[
			{
				"name":"user-form-individual",
				"type":"individual",
				"model":"User",
				"props":["user"],
			}
		]
	},
	{
		"name":"post",
		"folder":"post",
		"components":[
			{
				"name":"post-form",
				"type":"complete",
				"model":"Post",
				"props":["posts"]
			}
		]
	},
	{
		"name":"post-individual",
		"folder":"post",
		"controller":"PostController",
		"components":[
			{
				"name":"post-form-individual",
				"type":"individual",
				"model":"Post",
				"props":["post"],
			}
		]
	},
	{
		"name":"login",
		"folder":"login",
		"controller":"LoginController",
		"components":[
			{
				"name":"login-form",
				"type":"login",
				"model":"User"
			}
		]
	},
	{
		"name":"register",
		"folder":"register",
		"controller":"RegisterController",
		"components":[
			{
				"name":"register-form",
				"type":"register",
				"model":"User"
			}
		]
	},
]

g=Generator(project_path,project_name)
# g.init(vue=True)
# g.set_database(database_name,database_user,database_password)
# g.create_model(models)
# g.create_migration(models)
g.create_middleware(middlewares)
g.create_controller(controllers,models)
g.create_route(controllers)
g.create_views(views)
g.create_components(views,controllers,models)